keys:
  - &server_heureka age1cvv0jcnytk8zyw7q0qyqh34vuaz9ahxy8l0de96c80uje0tq893q9jgpej
  - &admin_heureka age129d0anamzkwl2exlcgf5p37qwpcgg4scljym7pf9xp049zeqnp7syka73a
  - &main_key_laptop age1lzr2tandayu8yw6wfh49slhl8hhwzz0phdldeemk5ryryqkwu9gqd0e7y8
creation_rules:
    - path_regex: secrets/[^/]+\.yaml$
      key_groups:
        - age:
          - *admin_heureka
          - *server_heureka
          - *main_key_laptop
